server:
  port:
    9090

spring:
  profiles:
    active:
      dev

  dev-profile:
    server:
      port:
        8080

  test-profile:
    server:
      port:
        7070

  prod-profile:
    server:
      port:
        8447

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ChatModule;encrypt=false
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 12345

  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.SQLServer2012Dialect
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
