server:
  port:
    9090

spring:
  profiles:
    active:
      dev

  dev-profile:
    server:
      port:
        8080

  test-profile:
    server:
      port:
        7070

  prod-profile:
    server:
      port:
        8447

  datasource:
    url: jdbc:h2:mem:defaultdb
    driverClassname: org.h2.Driver
    username: default
    password: 1234
  h2:
    console:
      enabled: true